variables:
    AWS_DEFAULT_REGION: "us-east-1"
    AWS_PROFILE: "oidc"

# oidc_test:
#     image:
#         name: amazon/aws-cli:latest
#         entrypoint: [""]
#     id_tokens:
#         MY_OIDC_TOKEN:
#             aud: https://gitlab.com
#     script:
#         - aws sts get-caller-identity

assume role:
    image:
        name: amazon/aws-cli:latest
        entrypoint: [""]
    id_tokens:
        MY_OIDC_TOKEN:
            aud: https://gitlab.com
    script:
        - >
          export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
          $(aws sts assume-role-with-web-identity
          --role-arn ${ROLE_ARN}
          --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
          --web-identity-token ${MY_OIDC_TOKEN}
          --duration-seconds 3600
          --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
          --output text))
        - aws sts get-caller-identity
        - aws s3 ls
        - aws s3 rb s3://elasticbeanstalk-us-east-1-811658952076 --force
